REQUESTED = "REQUESTED"
ACCEPTED = "ACCEPTED"
DRIVER_ARRIVING = "DRIVER_ARRIVING"
STARTED = "STARTED"
COMPLETED = "COMPLETED"
CANCELLED = "CANCELLED"

ACTIVE_RIDE_STATUSES = [
    ACCEPTED,
    DRIVER_ARRIVING,
    STARTED,
]

FINAL_RIDE_STATUSES = [
    COMPLETED,
    CANCELLED,
]
