# Generated by Django 6.0.7 on 2026-08-10 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ride_type', 'NOW'), ('scheduled_at__isnull', True)), models.Q(('ride_type', 'SCHEDULED'), ('scheduled_at__isnull', False)), _connector='OR'), name='valid_ride_schedule'),
        ),
    ]
