# Generated by Django 6.0.7 on 2026-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_valid_ride_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='rides_vehic_vehicle_d78590_idx'),
        ),
    ]
