# Generated by Django 6.0.7 on 2026-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='availability_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='ONLINE', max_length=10),
        ),
    ]
