# Generated by Django 6.0.7 on 2026-08-24 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_driverlocation_availability_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_user_id_50af28_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_driver__850520_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_status__c37074_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_created_fc9acb_idx',
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user', '-created_at'], name='ride_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-created_at'], name='ride_driver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', '-created_at'], name='ride_status_created_idx'),
        ),
    ]
